### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by iamjen023** [StashApp/StashServer#29]
i just want to share a icon i made for you to use with the app.
just something i throw together 
![stash](https://user-images.githubusercontent.com/27248541/45661279-6d998700-bac2-11e8-8c88-08d25db0dc5b.png)

**Comment by StashAppDev** [comment]
Thanks for the contribution!  This is much better than the default angular icon.  I went ahead and added it to the project.  Pull the latest code from the front end and it should show up.
