### ISSUE TITLE
password system

### ISSUE THREAD

**Issue by iamjen023** [stashapp/StashServer#30]
i would love a password to beable to view anything in the stash

**Comment by StashAppDev** [comment]
This is something that I've been thinking about, but I'm not sure how I might implement it yet.  How do you see this functioning?  The easiest way would be to just have a single password which allows full access after entry.  The better approach would probably be a proper account system with access control.  It's not something I would use personally, but I'm wondering if other users would find that useful.

**Comment by ExceptionalError** [comment]
Maybe the Password could be implemented in the reverse proxy?
I think a single, global password would be sufficient, it's just that people do not "stumble" on the stash.
A proper access control is way to overkill. How many people will be realisticly using the stash? Maybe 1 - 3?
