### ISSUE TITLE
sharing

### ISSUE THREAD

**Issue by iamjen023** [stashapp/StashServer#31]
i would like to have a system where i can share a video with someone.
i like it to have a time limit option.
so i could share "best porn video ever" with a friend and set it to expire at first view
times i like 
first view 15min 30min 1 hour 2 hours 4 hours 1 day custom never
also to trigger link expire now to revoke link anytime

**Comment by StashAppDev** [comment]
I'll have to think on this one.  To be honest the project was hacked together quickly.  I didn't have access control in mind when I built this, so this might take a bit of time to implement.
