### ISSUE TITLE
Integration of python scanner

### ISSUE THREAD

**Issue by ExceptionalError** [stashapp/StashServer#34]
Hi,

I have a couple of python scripts that do a very good job of identifying artists and tags from file name.
Currently I use them to consistently rename all of my files.
Would it be possible to integrate these in StashServer?
I have seen in the documentation that you have MD5 - json for performers and scenes.
These could be generated by the script. However I am not sure how to integrate tags since I don't have StashServer running (yet). Could you extend the documentation of the json-files a bit?
Do you think the coupling would be possible?

**Comment by StashAppDev** [comment]
This is totally possible.  The import script is here: https://github.com/StashApp/StashServer/blob/master/lib/stash/tasks/import.rb .  I'll try to document the schema when I'm able.
