### ISSUE TITLE
trello setup

### ISSUE THREAD

**Issue by iamjen023** [StashApp/StashServer#35]
i have setup a trello roadmap for you 
i tried to add things i thought would be helpful
i had some fun with it and expanded on my ideas 
and import some things i viewed on here
i could find a way to message you on here privately so i did it this way
if you send me a email iamjen023@gmail.com i will send you a link and tranfer the  trello page over to you i would like to verify it really you before i do it so i will ask you something in email and have to replay here as prove
once its under your control add to it or change it as you wish
i was bored and wanted to help this project in some way and being i cant code i thought of this
https://trello.com/b/UUXRqfBz/stashapp

**Comment by StashAppDev** [comment]
Thanks for the idea.  I'd like to keep everything project related contained within Github however.  It looks like they support trello-like functionality on the [projects](https://github.com/StashApp/StashServer/projects) tab, I might look into this instead.
