### ISSUE TITLE
patreon

### ISSUE THREAD

**Issue by iamjen023** [stashapp/StashServer#36]
please make a patreon so i can donate to this project to keep it going you will need to show it as a none adult tool but just add some youtube videos to it for patreon we all know what it really be used for but as great way to donate.
i supported pornganizer in the past but he havnt updated it in a while and not happy with it right now
i really would like to support this one instead

**Comment by echo6ix** [comment]
Yeah, I'd definitely donate to keep development going.

**Comment by StashAppDev** [comment]
While I appreciate the want to donate, I don't feel comfortable with that at this time for a couple of reasons:

1) If I take donations, then I'll feel like I'm obligated to put time into the project.  That is not something I can guarantee at this point in time.  I foresee myself being very time limited for the next several months.
2) I don't feel the project is user friendly enough to ask for donations at this point.  I've tried to help the best I can in these Github issues or the Slack channel, but I can't spend a ton of time on it.  Once I get the project to a point where it's a simple install then I'll feel more comfortable with this.

I'll leave this open for visibility, but as of now I don't have plans to do this.
