### ISSUE TITLE
ngrok Tunnel

### ISSUE THREAD

**Issue by iamjen023** [stashapp/StashServer#38]
im having trouble setting up a ngrok Tunnel.
i have mine installed as docker on unraid
setup with docker-compose
the Tunnel works showing the frontpage but if i go to one of this it just keeps loading and nothing happens
performers
galleries
scenes

ngrok setup
ive stuff with *'s is just random stuff i typed insetd of whats really there that is for my eyes only
#'s is commutes 
ngrok.yml

  GNU nano 2.5.3                             File: ngrok.yml

authtoken: 897fsao8u7f89yud89iq89*****68976789  # account key

tunnels: 

   stash:  # name of tunnel
    addr: 8008 # port to foward
    proto: http # type of tunnel
    subdomain: stash*****    # sub domain of ngrok so it be stash*****.ngrok.io
    auth: "user***:password****" # user and pass for tunnel
    bind_tls: false # only forwards http and not https
    inspect: false # turns off data passing though

**Comment by StashAppDev** [comment]
You likely need to forward another port.  The UI is served through port 8008 (on docker), but you also need port 4000 for the GraphQL API.

**Comment by iamjen023** [comment]
Ngrok only let's you open one port per url
So I went with noip.net
