### ISSUE TITLE
galleries stays in loading loop

### ISSUE THREAD

**Issue by iamjen023** [stashapp/StashServer#39]
when i view videos and browse videos and performers it loads instantly 
but when i view  galleries it just keep loading i let it set for 5 mins and nothing

**Comment by echo6ix** [comment]
Same issue here. It worked with one zip archive, but failed to load the gallery when I dropped in 29 more zip archives.

Deleted all zips.
rails metadata:cleanup

The landing page still shows a number of 30 galleries, and ip:8080/galleries still suck on the loading spinner

**Comment by iamjen023** [comment]
thanks for the info i looked into the sqlite3 file with this program
https://sqlitebrowser.org/
went to browse data then delete record
and wipe out all the info in the galleries table that reset it to 0

**Comment by StashAppDev** [comment]
If you're using chrome push Ctrl + Shift + I to open the dev tools and click on the console tab.  Check if there are any errors being logged.
